/**
 * src/constants/tabs.ts — All tab metadata (names, colors, gradients, sidebar data).
 * Single source of truth — edit here to add/remove/rename sections.
 */
import type { TabKey, SidebarData } from '@appTypes';

export const TAB_NAMES: Record<TabKey, string> = {
  react:       'React',
  graphql:     'GraphQL',
  angular:     'Angular',
  vue:         'Vue.js',
  browser:     'Browser',
  engine:      'JS Engine',
  es6:         'ES6+',
  'react-adv': 'React+',
  react19:     'React 19',
  build:       'Build Tools',
  nextjs:      'Next.js',
  patterns:    'Patterns',
  vitals:      'Web Vitals',
  security:    'Security',
  testing:     'Testing',
  prepqa:      'Prep Q\u0026A',
  backend:     'Backend',
  cicd:        'CI/CD \u0026 Deploy',
  hca:         'HTML/CSS/A11y',
  sdlc:        'SDLC',
};

export const TAB_COLORS: Record<TabKey, string> = {
  react:       '#8b7ae8',
  graphql:     '#e535ab',
  angular:     '#ef4444',
  vue:         '#34d399',
  browser:     '#3b82f6',
  engine:      '#f59e0b',
  es6:         '#c084fc',
  'react-adv': '#0ea5e9',
  react19:     '#0ea5e9',
  build:       '#f97316',
  nextjs:      '#a1a1aa',
  patterns:    '#a78bfa',
  vitals:      '#10b981',
  security:    '#ef4444',
  testing:     '#06b6d4',
  prepqa:      '#d97706',
  backend:     '#22c55e',
  cicd:        '#38bdf8',
  hca:         '#e44d26',
  sdlc:        '#f59e0b',
};

export const SIDEBAR_DATA: SidebarData = {
  react:       [
    { label: 'Component Architecture', id: 'react-arch'    },
    { label: 'Redux State Flow',        id: 'react-redux'   },
    { label: 'Zustand',                 id: 'react-zustand' },
    { label: 'Animated Diagram',        id: 'react-anim'    },
  ],
  graphql:     [
    { label: 'Apollo Architecture', id: 'gql-apollo'   },
    { label: 'Core Concepts',       id: 'gql-concepts'  },
    { label: 'Animated Diagram',    id: 'gql-anim'      },
  ],
  angular:     [
    { label: 'Architecture',     id: 'ng-arch' },
    { label: 'Animated Diagram', id: 'ng-anim' },
  ],
  vue:         [
    { label: 'Reactivity System', id: 'vue-arch' },
    { label: 'Animated Diagram',  id: 'vue-anim' },
  ],
  browser:     [
    { label: 'Rendering Pipeline', id: 'browser-pipeline'   },
    { label: 'DOM + CSSOM',        id: 'browser-render'     },
    { label: 'Middleware',         id: 'browser-middleware'  },
    { label: 'Animated Pipeline',  id: 'browser-anim'       },
  ],
  engine:      [
    { label: 'V8 Pipeline',          id: 'engine-pipeline'  },
    { label: 'Concepts',             id: 'engine-concepts'  },
    { label: 'Animated Diagram',     id: 'engine-anim'      },
    { label: 'WebSockets & Workers', id: 'engine-wsw'       },
  ],
  es6:         [
    { label: 'Event Loop',    id: 'es6-eventloop' },
    { label: 'Async/Await',   id: 'es6-async'     },
    { label: 'ES6 Features',  id: 'es6-features'  },
    { label: 'Modules',       id: 'es6-modules'   },
    { label: 'TypeScript',    id: 'es6-typescript' },
  ],
  'react-adv': [
    { label: 'React Fiber',      id: 'radv-fiber'         },
    { label: 'HOC',              id: 'radv-hoc'           },
    { label: 'Context API',      id: 'radv-context'       },
    { label: 'Portals',          id: 'radv-portal'        },
    { label: 'Fragments',        id: 'radv-fragment'      },
    { label: 'Error Boundaries', id: 'radv-errorboundary' },
  ],
  react19:     [
    { label: 'What is React 19', id: 'r19-overview'  },
    { label: 'New Hooks',        id: 'r19-hooks'     },
    { label: 'Server Actions',   id: 'r19-actions'   },
    { label: 'Asset Loading',    id: 'r19-assets'    },
    { label: 'React Compiler',   id: 'r19-compiler'  },
  ],
  build:       [
    { label: 'Webpack',          id: 'build-webpack'     },
    { label: 'Webpack Advanced', id: 'build-webpack-adv' },
    { label: 'Vite',             id: 'build-vite'        },
    { label: 'Webpack vs Vite',  id: 'build-compare'     },
    { label: 'Monorepo / NX',    id: 'build-monorepo'    },
  ],
  nextjs:      [
    { label: 'CSR',          id: 'next-csr'  },
    { label: 'SSR',          id: 'next-ssr'  },
    { label: 'App Router',   id: 'next-flow' },
  ],
  patterns:    [
    { label: 'Module',    id: 'pat-module'    },
    { label: 'Singleton', id: 'pat-singleton' },
    { label: 'Factory',   id: 'pat-factory'   },
    { label: 'Observer',  id: 'pat-observer'  },
    { label: 'Strategy',  id: 'pat-strategy'  },
  ],
  vitals:      [
    { label: 'Core Vitals',   id: 'vitals-overview'  },
    { label: 'Other Metrics', id: 'vitals-other'     },
    { label: 'Optimization',  id: 'vitals-optimize'  },
  ],
  security:    [
    { label: 'Threat Landscape', id: 'sec-overview'    },
    { label: 'XSS',              id: 'sec-xss'         },
    { label: 'CORS & CSRF',      id: 'sec-cors-csrf'   },
    { label: 'Scanning & Tools', id: 'sec-scanning'    },
  ],
  testing:     [
    { label: 'Testing Pyramid', id: 'test-pyramid'  },
    { label: 'Test Types',      id: 'test-types'    },
    { label: 'Test Patterns',   id: 'test-patterns' },
    { label: 'Tools Ecosystem', id: 'test-tools'    },
  ],
  prepqa:      [
    { label: 'Architecture (1-15)',      id: 'qa-arch'    },
    { label: 'Performance (16-25)',      id: 'qa-perf'    },
    { label: 'Design Systems (26-35)',   id: 'qa-design'  },
    { label: 'Tooling & Infra (36-45)', id: 'qa-infra'   },
    { label: 'Leadership (46-52)',       id: 'qa-collab'  },
    { label: 'Security (53-60)',         id: 'qa-security'},
    { label: 'React & Redux (61-80)',    id: 'qa-filter-react-redux',  qaFilter: 'react-redux'  },
    { label: 'JavaScript ES6+ (81-100)',id: 'qa-filter-javascript',   qaFilter: 'javascript'   },
    { label: 'System Design (101-120)', id: 'qa-filter-sysdesign',    qaFilter: 'sysdesign'    },
    { label: 'Next.js (121-140)',        id: 'qa-filter-nextjs-qa',    qaFilter: 'nextjs-qa'    },
    { label: 'Angular (141-160)',        id: 'qa-filter-angular-qa',   qaFilter: 'angular-qa'   },
    { label: 'Vue.js (161-180)',         id: 'qa-filter-vue-qa',       qaFilter: 'vue-qa'       },
    { label: 'GraphQL (181-200)',        id: 'qa-filter-graphql-qa',   qaFilter: 'graphql-qa'   },
    { label: 'Webpack & Vite (201-220)', id: 'qa-filter-webpack-vite', qaFilter: 'webpack-vite' },
  ],
  backend:     [
    { label: 'Node.js Event Loop',   id: 'be-node-overview'     },
    { label: 'Streams & Workers',    id: 'be-node-streams'      },
    { label: 'Clustering & PM2',     id: 'be-node-perf'         },
    { label: 'Express Middleware',   id: 'be-express-overview'  },
    { label: 'Express Architecture', id: 'be-express-patterns'  },
    { label: 'MongoDB Overview',     id: 'be-mongo-overview'    },
    { label: 'Aggregation',          id: 'be-mongo-aggregation' },
    { label: 'PostgreSQL',           id: 'be-pg-overview'       },
    { label: 'Advanced PG',          id: 'be-pg-advanced'       },
    { label: 'Full Stack',           id: 'be-stack-integration' },
  ],
  cicd:        [
    { label: 'Docker',       id: 'cicd-docker'   },
    { label: 'Kubernetes',   id: 'cicd-k8s'      },
    { label: 'Kafka',        id: 'cicd-kafka'    },
    { label: 'Vercel',       id: 'cicd-vercel'   },
    { label: 'CI/CD Pipeline', id: 'cicd-pipeline' },
  ],
  hca:         [
    { label: 'HTML5 Semantics', id: 'hca-html'          },
    { label: 'CSS Layout',      id: 'hca-css'           },
    { label: 'Accessibility',   id: 'hca-a11y'          },
    { label: 'SASS & LESS',     id: 'hca-preprocessors' },
  ],
  sdlc:        [
    { label: 'SDLC Overview',        id: 'sdlc-overview'  },
    { label: 'SDLC Phases Animation',id: 'sdlc-anim'      },
    { label: 'Software Architect',   id: 'sdlc-architect' },
    { label: 'MVC vs MVP vs MVVM',   id: 'sdlc-patterns'  },
    { label: 'TDD / BDD / ATDD',     id: 'sdlc-tdd'       },
  ],
};
